# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_admin_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_admin(object):
    def setupUi(self, add_admin):
        add_admin.setObjectName("add_admin")
        add_admin.resize(333, 364)
        self.label = QtWidgets.QLabel(add_admin)
        self.label.setGeometry(QtCore.QRect(40, 50, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(add_admin)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(add_admin)
        self.label_3.setGeometry(QtCore.QRect(40, 180, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(add_admin)
        self.label_4.setGeometry(QtCore.QRect(40, 230, 72, 15))
        self.label_4.setObjectName("label_4")
        self.uname = QtWidgets.QLineEdit(add_admin)
        self.uname.setGeometry(QtCore.QRect(140, 40, 113, 21))
        self.uname.setObjectName("uname")
        self.upassword = QtWidgets.QLineEdit(add_admin)
        self.upassword.setGeometry(QtCore.QRect(140, 90, 113, 21))
        self.upassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.upassword.setObjectName("upassword")
        self.urank = QtWidgets.QLineEdit(add_admin)
        self.urank.setGeometry(QtCore.QRect(140, 180, 113, 21))
        self.urank.setObjectName("urank")
        self.uphone = QtWidgets.QLineEdit(add_admin)
        self.uphone.setGeometry(QtCore.QRect(140, 230, 113, 21))
        self.uphone.setObjectName("uphone")
        self.add = QtWidgets.QPushButton(add_admin)
        self.add.setGeometry(QtCore.QRect(150, 290, 93, 28))
        self.add.setObjectName("add")
        self.label_5 = QtWidgets.QLabel(add_admin)
        self.label_5.setGeometry(QtCore.QRect(40, 140, 72, 15))
        self.label_5.setObjectName("label_5")
        self.doubleupassword = QtWidgets.QLineEdit(add_admin)
        self.doubleupassword.setGeometry(QtCore.QRect(140, 140, 113, 21))
        self.doubleupassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.doubleupassword.setObjectName("doubleupassword")

        self.retranslateUi(add_admin)
        QtCore.QMetaObject.connectSlotsByName(add_admin)

    def retranslateUi(self, add_admin):
        _translate = QtCore.QCoreApplication.translate
        add_admin.setWindowTitle(_translate("add_admin", "新建管理员"))
        self.label.setText(_translate("add_admin", "用户名："))
        self.label_2.setText(_translate("add_admin", "密码："))
        self.label_3.setText(_translate("add_admin", "等级："))
        self.label_4.setText(_translate("add_admin", "手机号码："))
        self.add.setText(_translate("add_admin", "注册"))
        self.label_5.setText(_translate("add_admin", "确认密码："))
