# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'carema_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_camera(object):
    def setupUi(self, camera):
        camera.setObjectName("camera")
        camera.resize(314, 235)
        self.label_camera_in = QtWidgets.QLabel(camera)
        self.label_camera_in.setGeometry(QtCore.QRect(58, 25, 240, 70))
        self.label_camera_in.setMouseTracking(True)
        self.label_camera_in.setAcceptDrops(True)
        self.label_camera_in.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_camera_in.setText("")
        self.label_camera_in.setObjectName("label_camera_in")
        self.label = QtWidgets.QLabel(camera)
        self.label.setGeometry(QtCore.QRect(13, 36, 51, 45))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(camera)
        self.label_2.setGeometry(QtCore.QRect(13, 151, 51, 45))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_camera_out = QtWidgets.QLabel(camera)
        self.label_camera_out.setGeometry(QtCore.QRect(58, 138, 240, 70))
        self.label_camera_out.setMouseTracking(True)
        self.label_camera_out.setAcceptDrops(True)
        self.label_camera_out.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_camera_out.setText("")
        self.label_camera_out.setObjectName("label_camera_out")

        self.retranslateUi(camera)
        QtCore.QMetaObject.connectSlotsByName(camera)

    def retranslateUi(self, camera):
        _translate = QtCore.QCoreApplication.translate
        camera.setWindowTitle(_translate("camera", "摄像头模拟器"))
        self.label.setText(_translate("camera", "进入"))
        self.label_2.setText(_translate("camera", "离开"))
