# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_admin_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_delete_admin(object):
    def setupUi(self, delete_admin):
        delete_admin.setObjectName("delete_admin")
        delete_admin.resize(400, 168)
        self.label = QtWidgets.QLabel(delete_admin)
        self.label.setGeometry(QtCore.QRect(50, 50, 121, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(delete_admin)
        self.lineEdit.setGeometry(QtCore.QRect(180, 50, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.cut = QtWidgets.QPushButton(delete_admin)
        self.cut.setGeometry(QtCore.QRect(190, 110, 93, 28))
        self.cut.setObjectName("cut")

        self.retranslateUi(delete_admin)
        QtCore.QMetaObject.connectSlotsByName(delete_admin)

    def retranslateUi(self, delete_admin):
        _translate = QtCore.QCoreApplication.translate
        delete_admin.setWindowTitle(_translate("delete_admin", "删除管理员"))
        self.label.setText(_translate("delete_admin", "输入删除的账号："))
        self.cut.setText(_translate("delete_admin", "删除"))
