# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogofCar_time.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogByTime(object):
    def setupUi(self, LogByTime):
        LogByTime.setObjectName("LogByTime")
        LogByTime.resize(640, 640)
        LogByTime.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        LogByTime.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.gridLayout = QtWidgets.QGridLayout(LogByTime)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(LogByTime)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.line = QtWidgets.QFrame(LogByTime)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CarNameInputPro = QtWidgets.QLabel(LogByTime)
        font = QtGui.QFont()
        font.setFamily("等线")
        self.CarNameInputPro.setFont(font)
        self.CarNameInputPro.setObjectName("CarNameInputPro")
        self.horizontalLayout.addWidget(self.CarNameInputPro)
        self.dateTime_begin = QtWidgets.QDateTimeEdit(LogByTime)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.dateTime_begin.setFont(font)
        self.dateTime_begin.setObjectName("dateTime_begin")
        self.horizontalLayout.addWidget(self.dateTime_begin)
        self.dataTime_end = QtWidgets.QDateTimeEdit(LogByTime)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.dataTime_end.setFont(font)
        self.dataTime_end.setObjectName("dataTime_end")
        self.horizontalLayout.addWidget(self.dataTime_end)
        self.CarNameConfirm = QtWidgets.QPushButton(LogByTime)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        self.CarNameConfirm.setFont(font)
        self.CarNameConfirm.setObjectName("CarNameConfirm")
        self.horizontalLayout.addWidget(self.CarNameConfirm)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(LogByTime)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.TableOfCarLog = QtWidgets.QTableView(LogByTime)
        self.TableOfCarLog.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.TableOfCarLog.setObjectName("TableOfCarLog")
        self.verticalLayout.addWidget(self.TableOfCarLog)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)

        self.retranslateUi(LogByTime)
        QtCore.QMetaObject.connectSlotsByName(LogByTime)

    def retranslateUi(self, LogByTime):
        _translate = QtCore.QCoreApplication.translate
        LogByTime.setWindowTitle(_translate("LogByTime", "车辆日志查询"))
        self.label.setText(_translate("LogByTime",
                                      "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#55aaff;\">车辆进出查询</span></p></body></html>"))
        self.CarNameInputPro.setText(_translate("LogByTime",
                                                "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">请输入停车区间：</span></p></body></html>"))
        self.CarNameConfirm.setText(_translate("LogByTime", "查询"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    LogByTime = QtWidgets.QDialog()
    ui = Ui_LogByTime()
    ui.setupUi(LogByTime)
    LogByTime.show()
    sys.exit(app.exec_())
