# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rate_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Rate(object):
    def setupUi(self, Rate):
        Rate.setObjectName("Rate")
        Rate.resize(1136, 88)
        self.gridLayout = QtWidgets.QGridLayout(Rate)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DoubleSpin = QtWidgets.QDoubleSpinBox(Rate)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(16)
        self.DoubleSpin.setFont(font)
        self.DoubleSpin.setObjectName("DoubleSpin")
        self.horizontalLayout.addWidget(self.DoubleSpin)
        self.RateSlider = QtWidgets.QSlider(Rate)
        self.RateSlider.setOrientation(QtCore.Qt.Horizontal)
        self.RateSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.RateSlider.setObjectName("RateSlider")
        self.horizontalLayout.addWidget(self.RateSlider)
        self.pushButton = QtWidgets.QPushButton(Rate)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(Rate)
        QtCore.QMetaObject.connectSlotsByName(Rate)

    def retranslateUi(self, Rate):
        _translate = QtCore.QCoreApplication.translate
        Rate.setWindowTitle(_translate("Rate", "费率设置"))
        self.pushButton.setText(_translate("Rate", "确定"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Rate = QtWidgets.QDialog()
    ui = Ui_Rate()
    ui.setupUi(Rate)
    Rate.show()
    sys.exit(app.exec_())
