# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.setEnabled(True)
        login.resize(400, 300)
        self.label = QtWidgets.QLabel(login)
        self.label.setGeometry(QtCore.QRect(118, 26, 239, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(login)
        self.label_2.setGeometry(QtCore.QRect(95, 86, 59, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(login)
        self.label_3.setGeometry(QtCore.QRect(95, 134, 66, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.input_username = QtWidgets.QLineEdit(login)
        self.input_username.setGeometry(QtCore.QRect(184, 86, 113, 20))
        self.input_username.setObjectName("input_username")
        self.input_password = QtWidgets.QLineEdit(login)
        self.input_password.setGeometry(QtCore.QRect(184, 134, 113, 20))
        self.input_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_password.setObjectName("input_password")
        self.radiobtn_social = QtWidgets.QRadioButton(login)
        self.radiobtn_social.setGeometry(QtCore.QRect(185, 179, 96, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.radiobtn_social.setFont(font)
        self.radiobtn_social.setObjectName("radiobtn_social")
        self.radiobtn_house = QtWidgets.QRadioButton(login)
        self.radiobtn_house.setGeometry(QtCore.QRect(263, 177, 95, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.radiobtn_house.setFont(font)
        self.radiobtn_house.setObjectName("radiobtn_house")
        self.btn_login = QtWidgets.QPushButton(login)
        self.btn_login.setGeometry(QtCore.QRect(162, 218, 60, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btn_login.setFont(font)
        self.btn_login.setObjectName("btn_login")
        self.label_4 = QtWidgets.QLabel(login)
        self.label_4.setGeometry(QtCore.QRect(95, 176, 68, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_tips = QtWidgets.QLabel(login)
        self.label_tips.setGeometry(QtCore.QRect(139, 253, 145, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_tips.setFont(font)
        self.label_tips.setText("")
        self.label_tips.setObjectName("label_tips")

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "登录"))
        self.label.setText(_translate("login", "欢迎登陆停车管理系统"))
        self.label_2.setText(_translate("login", "用户名："))
        self.label_3.setText(_translate("login", "密   码："))
        self.radiobtn_social.setText(_translate("login", "社会停车"))
        self.radiobtn_house.setText(_translate("login", "小区停车"))
        self.btn_login.setText(_translate("login", "登  录"))
        self.label_4.setText(_translate("login", "模   式："))
